---
apiVersion: v1
kind: Service
metadata:
  name: kubecost-service
  namespace: kubecost
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  selector:
    app: cost-analyzer
  type: LoadBalancer
  loadBalancerClass: eks.amazonaws.com/nlb
  ports:
  - name: tcp-model
    nodePort: 31514
    port: 9003
    protocol: TCP
    targetPort: 9003
  - name: tcp-frontend
    nodePort: 32709
    port: 9090
    protocol: TCP
    targetPort: 9090