---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: keda
  name: deployment-2048
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-2048
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-2048
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: sqs-reader-sa
      containers:
        - image: cnrock/2048:latest@sha256:fc83e30a245af39105bb658ff5348fb0dec812ce9b0ff31915b4dc2ab5dce849
          imagePullPolicy: Always
          name: app-2048
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: "40"
              memory: "90Gi"
              nvidia.com/gpu: "4" # 7B: 1 | 14B: 4 | 32B: 4 | 72B:
            limits:
              cpu: "48"
              memory: "96Gi"
              nvidia.com/gpu: "4" # 7B: 1 | 14B: 4 | 32B: 4 | 72B:
      automountServiceAccountToken: true
      tolerations:
        - key: nvidia.com/gpu
          value: "true"
          effect: "NoSchedule"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sqs-reader
  namespace: keda
  labels:
    app: deployment-2048
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-2048
  pollingInterval:  5   # Default: 30 seconds
  cooldownPeriod:  10   # Default: 300 seconds
  idleReplicaCount: 0   # Default: ignored
  minReplicaCount:  0   # Default: 0
  maxReplicaCount:  10   # Default: 100
  triggers:
  - type: aws-sqs-queue
    metadata:
      queueURL: ""
      queueLength: "1"
      awsRegion: us-west-2
      identityOwner: operator
